#!/bin/sh

# disallow binary files and large files unless BINARY or LARGE tag in commit msg

commit_msg_file="$1"

if ! grep -q "BINARY" "$commit_msg_file"; then
    # numstat prints '-' for the number of added/deleted lines for binary files
    if git diff --cached --numstat --diff-filter=ACM | grep -q '^-'; then
        echo "ERROR: binary file(s) - add 'BINARY' to commit message" >&2
        exit 1
    fi
fi

if ! grep -q "LARGE" "$commit_msg_file"; then
    git diff --cached --name-only --diff-filter=ACM |
    while read -r file; do
        name="$(git ls-files --format='%(objectname)' "$file")"
        size="$(git cat-file -s "$name")"
        if [ "$size" -gt 1048576 ]; then
            echo "ERROR: large file(s) - add 'LARGE' to commit message" >&2
            exit 1
        fi
    done
fi
