alias python=python3
alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"
export MYVIMRC="$HOME/.config/vim/vimrc"
export VIMINIT="source $MYVIMRC"

stty -ixon      # disable Ctrl-S and Ctrl-Q

function dock {
    docker run --hostname docker -it -v ~/docker:/home/$(whoami) "$1"
}

function vm {
    local name=${1:-dev}
    local username=${2:-admin}
    if ! VBoxManage list runningvms | cut -d '"' -f 2 | grep -q "$name"; then
        VBoxManage startvm --type headless "$name"
        echo "Waiting for SSH connection..."
    fi
    local port=$(VBoxManage showvminfo "$name" --machinereadable |
                 grep '^Forwarding(.*,22"' | cut -d, -f4)
    ssh -p $port -o ConnectionAttempts=60 $username@localhost
}

function pause {
    local name=${1:-vm}
    VBoxManage controlvm "$name" pause
}

function title {
    echo -n -e "\033]0;$1\007"
}

function notify {
  message="${1:-Process complete}"
  options='title "Terminal" sound name "Ping"'
  script="display notification \"$message\" with $options"
  /usr/bin/osascript -e "$script"
}
