alias python=python3
alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"

export PS1="$ "
export CLICOLOR=1      # enable colored output for ls on OSX
export SHELL_SESSION_HISTORY=0
export HISTFILE="$HOME/.local/share/bash/history"
export MYVIMRC="$HOME/.config/vim/vimrc"
export VIMINIT="source $MYVIMRC"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"
export PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"

stty -ixon      # disable Ctrl-S and Ctrl-Q

function dock {
    docker run --hostname docker -it -v ~/docker:/home/$(whoami) "$1"
}

function vm {
    local name=${1:-Arch}
    local username=${2:-clark}
    if ! VBoxManage list runningvms | cut -d '"' -f 2 | grep -q "$name"; then
        VBoxManage startvm --type headless "$name"
        echo "Waiting for SSH connection..."
    fi
    local port=$(VBoxManage showvminfo "$name" --machinereadable |
                 grep '^Forwarding(.*,22"' | cut -d, -f4)
    ssh -p $port -o ConnectionAttempts=60 $username@localhost
}

function pause {
    local name=${1:-Arch}
    VBoxManage controlvm "$name" pause
}

function title {
    echo -n -e "\033]0;$1\007"
}

function notify {
  message="${1:-Process complete}"
  options='title "Terminal" sound name "Ping"'
  script="display notification \"$message\" with $options"
  /usr/bin/osascript -e "$script"
}
